---
# Author: Jared Marcuccilli
# Date: 10/24/2020
# Version 1.0
# Operations test: TBD
# Security test: TBD
# Problems addressed: TBD
# Description: Switch prod-loadbalancer to use A web servers.

- hosts: prod_loadbalancer
  become: true
  tasks:
  
    - name: Update to use A servers in haproxy.cfg
      blockinfile:
        path: /etc/haproxy/haproxy.cfg
        marker: "{mark}"
        marker_begin: "# START ANSIBLE MANAGED BLOCK"
        marker_end: "# END ANSIBLE MANAGED BLOCK"
        block: |
          backend http_back
            balance roundrobin
            server prod-web1 192.168.201.207:80 check
            server prod-web2 192.168.203.91:80 check
            server prod-web3 192.168.202.157:80 check

    - name: Restart haproxy
      service:
        name: haproxy
        state: restarted
